version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ordersapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18wgoagiwce9s"
s3_prefix = "ordersapi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
