AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  orders-api

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: orders_api/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64