AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  first-lambda

  Sample SAM Template for first-lambda

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: datatypes.cold_start_basics
      Runtime: python3.8
      Timeout: 7
      Environment:
        Variables:
          restapiurl: http://jrm2087.com
          dbname: mydb