version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-lambda-lab-jdrodrig"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10f1yol11sxmw"
s3_prefix = "aws-lambda-lab-jdrodrig"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
